branches:
  only:
    - master

git:
  depth: 10

env:
  global:
    - HUGO_ENV=production

before_install:
  - sudo apt-get update
  - sudo apt-get install -y hugo

script:
  - hugo --gc --minify

deploy:
  provider: pages
  edge: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public