language: go

go:
  - "1.13"

sudo: false

branches:
  only:
    - master

git:
  depth: 10

env:
  global:
    - HUGO_ENV=production

before_install:
  - sudo apt-get update

install:
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - go install --tags extended
  - cd $TRAVIS_BUILD_DIR

script:
  - hugo --gc --minify

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: public