language: go

go:
  - "1.14"

sudo: false

branches:
  only:
    - master

git:
  depth: 10

env:
  global:
    - HUGO_ENV=production

before_install:
  - sudo apt-get update
  - sudo apt install curl

install:
  - curl -fsSL https://github.com/gohugoio/hugo/releases/download/v0.72.0/hugo_0.72.0_Linux-64bit.deb -o /tmp/hugo.deb
  - cd /tmp
  - dpkg -i hugo.deb
  - cd $TRAVIS_BUILD_DIR

script:
  - hugo -D --gc --minify

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: public