baseURL = "/"
languageCode = "en-us"
title = "Neurobits"
theme = "leaveit"

enableRobotsTXT = true
enableEmoji = true
googleAnalytics = "UA-169749457-1"

[menu]
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 4

  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 2

[Permalinks]
  posts = "/:year/:filename"

[params]
  since = 2018
  author = "Rubens Santos"
  avatar = "/images/avatar.jpeg"
  subtitle = "follow me"

  description = "My personal blog"
  keywords = "data engineering,IT,infrastructure,devops,development"

[params.social]
  Github = "santosr2"
  Twitter = "santosr_2"
  Medium = "@santosr2"
